# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'

- 'on': ['Linux', 'FreeBSD', 'macOS', 'Windows']
  'require':
    'frameworks/kcoreaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kdoctools': '@stable'
