# SPDX-FileCopyrightText: 2024-2026 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: minuet
confinement: strict
grade: stable
base: core24
adopt-info: minuet
apps:
  minuet:
    extensions:
      - kde-neon-6
    common-id: org.kde.minuet.desktop
    desktop: usr/share/applications/org.kde.minuet.desktop
    command: usr/bin/minuet
    plugs:
      - audio-playback
      - home
environment:
  ALSA_CONFIG_PATH: "$SNAP/kf6/etc/asound.conf"
layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.minuet
    bus: session
parts:
  fluidsynth:
    source: https://github.com/FluidSynth/fluidsynth.git
    source-tag: v2.5.3
    plugin: cmake
    build-snaps:
      - kde-qt6-core24-sdk/latest/stable
      - kf6-core24-sdk/latest/stable
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-0t64
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
  minuet:
    after:
      - fluidsynth
    parse-info:
      - usr/share/metainfo/org.kde.minuet.metainfo.xml
    plugin: cmake
    source: .
    source-type: local
    build-snaps:
      - kde-qt6-core24-sdk/latest/stable
      - kf6-core24-sdk/latest/stable
    build-packages:
      - libasound2-dev
      - libdrumstick-dev
    stage-packages:
      - libasound2
      - libdrumstick-alsa2
      - libdrumstick-file2
      - libdrumstick-rt2
      - libasound2-data
      - libasound2-plugins
      - gstreamer1.0-alsa
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - oxygen-sounds
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/lib/aspell/*
      - -usr/share/lintian
  gpu-2404:
    after: [minuet]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  cleanup:
    after:
      - minuet
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done
